---
- name : libselinux-pythonとepelリポジトリのインストール
  yum :
    name : "{{ item }}"
    state : present
  with_items :
    - libselinux-python
    - epel-release
- name : Nginxのインストール
  yum :
    name : nginx
    state : present
- name : httpdの停止
  service :
   name : httpd
   state : stopped
- name : Nginxの起動と自動起動設定
  service :
   name : nginx
   state : started
   enabled : true
- name : firewallの停止
  service :
   name : firewalld
   state : stopped
   enabled : true
- name : nginx.confテンプレートを展開
  template :
    src : nginx.j2.conf
    dest : /etc/nginx/nginx.conf
    validate : nginx -t -c %s
  notify :
    - Nginxをリロード
- name : networkの再起動
  service :
   name : network
   state : restarted
   enabled : true
